apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-mind
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sawan-devrani/infra-mind.git
    targetRevision: main 
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-mind-app
  syncPolicy:
    automated:
      prune: true        
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true 
