name: Infra-Mind DevSecOps Pipeline

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

on:
  push:
    branches:
      - '**'          # Matches every single branch
      - '!main'       # Excludes the main branch
      - '!master'     # Excludes the master branch

permissions:
  contents: write
  security-events: write
  actions: read
  packages: write

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/infra-mind
  IMAGE_TAG: ${{ github.sha }}
  PYTHON_VERSION: "3.11"

jobs:
#   gitleaks:
#     name: Secret Scan - Gitleaks
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
#         with:
#           fetch-depth: 0

#       - name: Run Gitleaks
#         uses: gitleaks/gitleaks-action@v2
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           args: detect --source . --redact --verbose --exit-code 1

#   sca:
#     name: SCA - Python Dependencies
#     runs-on: ubuntu-latest
#     needs: gitleaks
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: ${{ env.PYTHON_VERSION }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi
#           pip install safety

#       - name: Run Safety scan
#         run: safety check --full-report

#   semgrep:
#     name: SAST - Semgrep
#     runs-on: ubuntu-latest
#     needs: gitleaks
#     container:
#       image: returntocorp/semgrep:latest
#     permissions:
#       security-events: write
#       contents: read
#       actions: read
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

#       - name: Run Semgrep scan
#         run: |
#           semgrep scan \
#             --config p/security-audit \
#             --config p/python \
#             --config p/secrets \
#             --sarif \
#             --output semgrep-results.sarif \
#             .

#       - name: Upload SARIF to GitHub Security
#         if: always()
#         uses: github/codeql-action/upload-sarif@v3
#         with:
#           sarif_file: semgrep-results.sarif

# #   sonarqube:
# #     name: SAST - SonarQube
# #     runs-on: ubuntu-latest
# #     needs: gitleaks
# #     steps:
# #       - name: Checkout code
# #         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
# #         with:
# #           fetch-depth: 0

# #       - name: Run SonarQube scan
# #         uses: SonarSource/sonarqube-scan-action@v3
# #         env:
# #           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
# #           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}




  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/infra-mind:${{ github.sha }}
          outputs: type=docker,dest=${{ runner.temp }}/image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tar
          path: ${{ runner.temp }}/image.tar

  image-scan:
    name: Container Scan - Trivy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar

      - name: Load image
        run: docker load -i image.tar

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 1
          severity: CRITICAL #,HIGH
          ignore-unfixed: true

      - name: Generate SARIF report
        if: always()
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

  push:
    name: Push Image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
            name: image-tar

      - name: Load image
        run: docker load -i image.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag image
        run: |
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/infra-mind:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/infra-mind:latest
      - name: Push versioned image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/infra-mind:${{ github.sha }}

      - name: Push latest image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/infra-mind:latest


  update-manifest:
    name: Update Deployment Tag
    runs-on: ubuntu-latest
    needs: push
    if: github.event_name == 'push' 
    # && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update image tag
        run: |
          sed -i "s|image: .*|image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g" k8s/deployment.yaml

      - name: Commit and push manifest update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "ci: update image tag to ${{ env.IMAGE_TAG }}" || exit 0
          git push
